In [63]:
import pandas as pd

In [64]:
st = pd.read_csv('/home/ifmt-aluno/Downloads/Cotação_do_dollar.csv')

In [65]:
st

         data   valor
0    01/01/26  5.5181
1    02/01/26    5.53
2    03/01/26    5.49
3    04/01/26    5.47
4    05/01/26    5.45
..        ...     ...
112  23/04/26  5.2136
113  24/04/26    5,00
114  25/04/26    5,00
115  26/04/26    5,00
116  27/04/26  5.0056

[117 rows x 2 columns]

In [66]:
st.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    117 non-null    object
 1   valor   117 non-null    object
dtypes: object(2)
memory usage: 2.0+ KB

In [67]:
st['data'] = pd.to_datetime(st['data'], dayfirst=True)

/tmp/ipykernel_15234/1072971449.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  st['data'] = pd.to_datetime(st['data'], dayfirst=True)

In [68]:
st.set_index('data', inplace=True)

In [69]:
st.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 117 entries, 2026-01-01 to 2026-04-27
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valor   117 non-null    object
dtypes: object(1)
memory usage: 1.8+ KB

In [70]:
st = st.asfreq('D')

In [71]:
st.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 117 entries, 2026-01-01 to 2026-04-27
Freq: D
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valor   117 non-null    object
dtypes: object(1)
memory usage: 1.8+ KB

In [72]:
st

             valor
data
2026-01-01  5.5181
2026-01-02    5.53
2026-01-03    5.49
2026-01-04    5.47
2026-01-05    5.45
...            ...
2026-04-23  5.2136
2026-04-24    5,00
2026-04-25    5,00
2026-04-26    5,00
2026-04-27  5.0056

[117 rows x 1 columns]

In [73]:
st.plot()

TypeError: no numeric data to plot

In [74]:
st.dropna(inplace=True)

In [75]:
st

             valor
data
2026-01-01  5.5181
2026-01-02    5.53
2026-01-03    5.49
2026-01-04    5.47
2026-01-05    5.45
...            ...
2026-04-23  5.2136
2026-04-24    5,00
2026-04-25    5,00
2026-04-26    5,00
2026-04-27  5.0056

[117 rows x 1 columns]

In [76]:
st.plot()

TypeError: no numeric data to plot